make gcc_5 happy
Later gcc versions are happy, but not the gcc_5 build:

/home/runner/work/minetest/minetest/src/client/tile.cpp:2233:14: error: ‘fmod’ is not a member of ‘std’
    hsl.Hue = std::fmod(hsl.Hue + hue, 360);
/home/runner/work/minetest/minetest/src/client/tile.cpp:2323:21: error: ‘fabs’ is not a member of ‘std’
  double slope = 1 - std::fabs(norm_b);
/home/runner/work/minetest/minetest/src/client/tile.cpp:2327:17: error: ‘atan’ is not a member of ‘std’
  double angle = std::atan(slope);
/home/runner/work/minetest/minetest/src/client/tile.cpp:2331:10: error: ‘tan’ is not a member of ‘std’
  slope = std::tan(angle);

camera.cpp still uses std:fabs() and doesn't cause any errors, I think because it uses '#include <cmath>', so that's another possible solution.